name: LuckyBoxes
version: '2.0'
main: me.basmty.luckyboxes.LuckyBoxes
author: iBasmaty
api-version: '1.13'
load: POSTWORLD
commands:
  boxes:
    description: main plugin command.
    aliases:
      - LuckyBoxes
      - luckyboxes